data:
  batch_size: 32
  color_jitter_strength: 0.0
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 224   
  image_folder: ''
  num_workers: 8
  pin_mem: true
  root_path: ''
  texture_root: "/home/ec2-user/SageMaker/breast_data/merts_fold3_breast_all/enhanced"
  depth_root: "/home/ec2-user/SageMaker/breast_data/merts_fold3_breast_all/bmode"
  thermal_root: "/home/ec2-user/SageMaker/breast_data/merts_fold3_breast_all/imp"
  csv_root:  "/home/ec2-user/SageMaker/channel_mix_i-jepa/ijepa_channel-mix_ft/ijepa/csv"
  use_color_distortion: false
  use_gaussian_blur: false
  use_horizontal_flip: false
logging:
  folder: "/home/ec2-user/SageMaker/channel_mix_i-jepa/log"
  write_tag: jepa
mask:
  allow_overlap: false
  aspect_ratio:
  - 0.75
  - 1.5
  enc_mask_scale:
  - 0.85
  - 1.0
  min_keep: 10
  num_enc_masks: 1
  num_pred_masks: 4
  patch_size: 14
  pred_mask_scale:
  - 0.15
  - 0.2
meta:
  copy_data: false
  load_checkpoint: true
  model_name: vit_small   ###burası onceden vit large dı ve parametreler de ona göre ayarllanmıs olabilir.
  pred_depth: 6  #vit base de init model de pred depth ve pred emb dime böyle demisler 
  pred_emb_dim: 192
  read_checkpoint: null
  use_bfloat16: true

optimization:
  ema:
  - 0.996
  - 1.0
  #50 idi epoch
  epochs: 10
  final_lr: 1.0e-06
  final_weight_decay: 0.4 
  ipe_scale: 1.0
  lr: 1.0e-3
  start_lr: 0.0001
  warmup: 0
  weight_decay: 0.01
