data:
  batch_size: 16
  color_jitter_strength: 0.0
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 224   
  image_folder: Breast_Data/backup_pretrain_rar_miccai_busı_fold1/fold1
  num_workers: 8
  pin_mem: true
  root_path: "/home/ec2-user/SageMaker/Breast_Data/backup_pretrain_rar_miccai_busı_fold1/fold1"
  use_color_distortion: false
  use_gaussian_blur: false
  use_horizontal_flip: false
logging:
  folder: "log"
  write_tag: jepa
mask:
  allow_overlap: false
  aspect_ratio:
  - 0.75
  - 1.5
  enc_mask_scale:
  - 0.85
  - 1.0
  min_keep: 10
  num_enc_masks: 1
  num_pred_masks: 4
  patch_size: 14
  pred_mask_scale:
  - 0.15
  - 0.2
meta:
  copy_data: false
  load_checkpoint: true
  model_name: vit_large   ###burası onceden vit large dı ve parametreler de ona göre ayarllanmıs olabilir.
  pred_depth: 12   #vit base de init model de pred depth ve pred emb dime böyle demisler 
  pred_emb_dim: 384
  read_checkpoint: null
  use_bfloat16: true

optimization:
  ema:
  - 0.996
  - 1.0
  epochs: 50
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 1.0e-2
  start_lr: 0.0001
  warmup: 5
  weight_decay: 0.05
